#!/usr/bin/env bash
#configures ubuntu machine to install nginx, listen:80, serve page

sudo apt-get -y update
sudo apt-get -y install nginx

#listen on 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

#create "Hello World" page to serve
echo hello world > /var/www/html/index.nginx-debian.html

service nginx start
