#!/usr/bin/env bash
#configures ubuntu machine to install nginx, listen:80, serve page

sudo apt-get -y update
sudo apt-get -y install nginx

#allow incoming traffic on port 80
ufw allow 'Nginx HTTP'

#create "Hello World" page to serve
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

service nginx start
