#!/usr/bin/env bash
# Debugging a server in an ubuntu container, process explained in README
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
