#!/usr/bin/env bash
# Debugging a server in an ubuntu container, process explained in README
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
pkill -x nginx
