#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and luck
fizz=1
while [ $fizz -le 100 ]
do
	if [ $(($fizz % 3)) -eq 0 ] && [ $(($fizz % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $(($fizz % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $(($fizz % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $fizz
	fi
	((fizz++))
done
