#!/usr/bin/env bash
# This script is displaying content of /etc/passwd
while IFS=':' read -r uname passwd uid gid inf hme shell;
do
	echo echo "The user $uname is part of the $gid gang,"\
  "lives in $hme and rides $shell."\
  "$uid's place is protected by the passcode $passwd,"\
  "more info about the user here: $inf"
done < '/etc/passwd'
