#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and luck
min=0
hr=0
while [ $hr -lt 13 ]
do
	echo "Hour: $hr"
	min=1
	while [ $min -lt 60 ]
	do
		echo $min
		((min++))
	done
	((hr++))
done
