#!/usr/bin/env bash
# This script is displaying content of current dir
# In list format
#only part of the name after the first dash is displayed
list=$(ls)
for l in $list; do
	echo "$l" | cut -d '-' -f2
done
