#!/usr/bin/env bash
# This script is giving you information about the school file
Sfile="./school"
if [ -e "$Sfile" ]
then
	echo "school file exists"
	if [ -s "$Sfile" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$Sfile" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
