#!/usr/bin/env bash
# This script changes localhost to 127.0.0.2
# and facebook.com to 8.8.8.8

cp /etc/hosts ~/hsts
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hsts
cp -f ~/hsts /etc/hosts
