#!/usr/bin/env bash
#runs nginx as the user nginx
chown -R nginx:nginx /etc/nginx /var/log/nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/'  /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sed -i 's/Listen 8080/Listen 80/' /etc/apache2/ports.conf
service apache2 restart
service nginx stop
su -c "nginx -c /etc/nginx/nginx.conf" nginx
