#!/usr/bin/env bash
#runs nginx as the user nginx
chown -R nginx:nginx /etc/nginx
chown 755 /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
